---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(readxl)
library(stringr)
library(ggplot2)
library(rvest)
library(pdftools)
library(tabulapdf)
library(glue)
library(rvest)
library(lubridate)
```

```{r}
source("functions.R")
```
Urls

```{r}
prison_webpage <- "https://www.sw.gov.pl/strona/Statystyka"

read_html(prison_webpage) |>
  html_nodes("div.files > div.file") |>
  html_text() |>
  str_remove_all("\\r|\\n") |>
  str_trim() |>
  str_replace_all("\\s{1,}", " ") -> pdf_names

read_html(prison_webpage) |>
  html_nodes("div.files > div.file") |>
  html_node("a") |> 
  html_attr("href") -> pdf_links

prison_pdf_reports <- data.frame(
  pdf_names,
  pdf_links = paste0("https://www.sw.gov.pl", pdf_links)
)
prison_pdf_reports <- prison_pdf_reports[-c(1,2), ] |>
  transform(type = str_extract(pdf_links, "(docx|pdf|xls|xlsx)$"))

tail(prison_pdf_reports)

months_pl <- c("styczeń"="01", "styczen"="01", "stycznia"="01",
  "luty"="02", "lutego"="02",
  "marzec"="03", "marca"="03",
  "kwiecień"="04", "kwiecien"="04", "kwietnia"="04",
  "maj"="05", "maja"="05",
  "czerwiec"="06", "czerwca"="06",
  "lipiec"="07", "lipca"="07",
  "sierpień"="08", "sierpien"="08", "sierpnia"="08",
  "wrzesień"="09", "wrzesien"="09", "września"="09", "wrzesnia"="09",
  "październik"="10", "pazdziernik"="10", "października"="10", "pazdziernika"="10",
  "listopad"="11", "listopada"="11",
  "grudzień"="12", "grudzien"="12", "grudnia"="12")

prison_pdf_reports <- prison_pdf_reports |>
  transform(
    filename = paste0(
      str_extract(pdf_names, "\\d{4}"),  
      "-",
      months_pl[str_extract(tolower(pdf_names), paste(names(months_pl), collapse="|"))],  # miesiąc
      ".",
      type  # rozszerzenie
    )
  ) |>
  transform(path = paste0("../data-raw/pdfs/", filename))

head(prison_pdf_reports)
saveRDS(prison_pdf_reports, file = "../data-raw/links-pdf-xlsx.rds")
```

Data processed by Aniela (from 2020, September)

```{r}
f_excel <- "../data-raw/wiezienia_excel.xlsx"
sheets <- excel_sheets(f_excel)
prisons <- data.table(sheets)
head(prisons)
```


# Process excel files


```{r}
d <- lapply(prisons$sheets, \(x) {
  doc <- read_excel(f_excel, sheet = x)
  subset(doc, panstwo != "Ogółem")
})
names(d) <- prisons$sheets
d_long <- rbindlist(d, idcol = "month_sheet")
d_long[, year:=str_extract(month_sheet, "\\d{4}")]
d_long[, month:=month_to_number(month_sheet)]
d_long[, panstwo:=str_to_lower(str_trim(panstwo))]
d_long[, iso3c := polish_to_iso3c(panstwo)]
d_long[, corrected:=str_detect(month_sheet, "korekta tabl")]
d_long[, month_sheet:=NULL]
d_long[, names(d_long)[2:10] := lapply(.SD, as.numeric), .SDcols = names(d_long)[2:10]]
d_long[is.na(k_skazane), k_skazane := 0]
df_long <- melt(d_long, id.vars = c("year", "month", "panstwo", "iso3c", "corrected"))
df_long[, c("sex", "category") := tstrsplit(variable, "_")]
df_long <- df_long[sex %in% c("k", "m") & !category %in% c("razem", NA)]
df_long[, variable:= NULL]
setcolorder(df_long, c("year", "month", "panstwo", "iso3c", "corrected", "sex", "category"))
setorderv(df_long, c("year", "month"))
df_long <- df_long[value != 0]
df_long[, corr:=uniqueN(corrected), .(year, month)]
df_long <- df_long[corr == 1 | (corr == 2 & corrected == TRUE)]
df_long[, corr:=NULL]
df_long[, corrected:=NULL]
df_long[, category := fcase(category %in% c("skazani", "skazane"), "convicted", 
                            category %in% c("ukarani", "ukarane"), "punished",
                            category %in% "tymczas", "temporary")]
df_long[, .N, category]
setnames(df_long, "panstwo", "country")
fwrite(df_long, file = "../data/prison-data.csv")
```

```{r}
df_long[, .(val=sum(value)), .(ym=str_c(year, "-", month), category)] |>
  ggplot(data = _, aes(x = ym, y= val, group = category, color = category)) +
  geom_line()

df_long[, .(val=sum(value)), .(ym=str_c(year, "-", month))] |>
  dput()
```


# Download data from 2010


```{r}
prison_pdf_reports |> 
  subset(!str_detect(filename, "NA")) |>
  subset(
    (as.numeric(str_extract(filename, "\\d{4}")) == 2010 & as.numeric(str_remove(str_extract(filename, "-\\d{2}"), "-")) >=4) |
     as.numeric(str_extract(filename, "\\d{4}")) %in% 2011:2019 |
    (as.numeric(str_extract(filename, "\\d{4}")) == 2020 & as.numeric(str_remove(str_extract(filename, "-\\d{2}"), "-")) < 9)
  ) -> files_to_download

setDT(files_to_download)
files_to_download <- files_to_download[order(filename)]
```

Download pdf files

```{r}
for (i in 15:NROW(files_to_download)) {
  download.file(url = files_to_download$pdf_links[i],
                destfile = files_to_download$path[i])
}
```


```{r}
pages <- numeric() 

pdf_to_process <- files_to_download[type == "pdf"]

for (i in 1:NROW(pdf_to_process)) {
  
  if (!file.exists(pdf_to_process$path[i])) {
    pages[i]  <- NA
    next
  }
  pdf_file_txt <- pdftools::pdf_text(pdf_to_process$path[i])  

pages[i] <- pdf_file_txt[2] |>
  trimws() |> 
  str_split("\\n") |>
  {\(x) x[[1]]}() |>
  {\(x) x[str_detect(x, regex("cudzoziemcy|obcokrajowcy", T))]}() |>
  {\(x) as.numeric(str_extract(x, "\\d{2}$"))}()

}

pdf_to_process$page <- pages + 3 
```

Extract specific pages and save them into one pdf

```{r}
dir.create("../data-raw/pdf-single-pages")
```

```{r}
pdf_to_process_singles <- subset(pdf_to_process, !is.na(page))
pdf_to_process_singles <- pdf_to_process_singles[order(path)]

for (i in 1:NROW(pdf_to_process_singles)) {
  system(glue("pdftk {pdf_to_process_singles$path[i]} cat {pdf_to_process_singles$page[i]} output {paste0('../data-raw/pdf-single-pages/', basename(pdf_to_process_singles$path[i]))}"))
}
```

Combine into one pdf

```{bash}
pdftk ../data-raw/pdf-single-pages/*.pdf cat output ../data-raw/prison-cudzoziemcy.pdf
```

Read data parsed via the Mathpix parsing of pdf

```{r}
d <- read_html("../data-raw/prison-cudzoziemcy.html") |>
  html_nodes("div.table") |>
  html_table()

for (i in which(sapply(d, ncol) %in% 12:13)) {
  d[[i]]$X11 <- d[[i]]$X12
  d[[i]]$X12 <- NULL
  d[[i]]$X13 <- NULL
}

file_names <- read_html("../data-raw/prison-cudzoziemcy.html") |>
  html_nodes("div.caption_table") |>
  html_text() ## 124

names(d) <- str_extract(file_names, "\\d{2}.\\d{2}.\\d{4}")

prison_pdf_df <- rbindlist(d, idcol = "plik", fill = T)
prison_pdf_df[, plik:=as.Date(plik, "%d.%m.%Y")]
prison_pdf_df <- prison_pdf_df[!X2 %in% c("Obywatelstwo", "Ogółem")]
prison_pdf_df[, X12:=NULL]
prison_pdf_df[, (paste0("X", 3:11)) := lapply(.SD, as.numeric), .SDcols = paste0("X", 3:11)]

setnames(prison_pdf_df,
         names(prison_pdf_df),
         c("plik", "lp", "country", 
           "total",
           "m_total", "m_temporary", "m_convicted", "m_punished",
           "k_total", "k_temporary", "k_convicted", "k_punished"
           ))

prison_pdf_df <- prison_pdf_df[country != ""]
prison_pdf_df <- prison_pdf_df[country != "powrót do spisu treści"]
prison_pdf_df <- prison_pdf_df[country != "powrót do spisu"]

prison_pdf_df[, country:=str_to_lower(str_trim(country))]
prison_pdf_df[, iso3c := polish_to_iso3c(country)]
prison_pdf_df[, year:=year(plik)]
prison_pdf_df[, month:=month(plik)]
prison_pdf_df[, month := as.numeric(month)]


prison_pdf_df[, plik:= NULL]
prison_pdf_df[, lp:= NULL]

prison_pdf_df <- prison_pdf_df |>
  melt(id.vars = c("year", "month", "country", "iso3c")) |>
  subset(variable != "total")

prison_pdf_df[, c("sex", "category") := tstrsplit(variable, "_")]
prison_pdf_df[, variable:=NULL]
setcolorder(prison_pdf_df, c("year", "month", "country", "iso3c", "sex", "category"))

prison_pdf_df[category != "total", .(value = sum(value, na.rm=T)), .(year, month)]
```

30.11.2018 r. - 1053 zamiast 1043
31.03.2019 r - 1115 vs 1125
od 2020 robi sie 1700 zamiast 1309 -- do sprawdzenia

```{r}
prison_all <- rbind(df_long, prison_pdf_df)
prison_all <- prison_all[order(year, month)]
prison_all[,.N, .(p=paste0(year,"-",month))]
prison_all[, .(m=uniqueN(month)), year]
prison_all <- prison_all[value > 0]
prison_all <- prison_all[category != "total"]
```

```{r}
fwrite(prison_all, file = "../data/prison-data-2010-2025.csv")
```

```{r}
writexl::write_xlsx(x = prison_all, path = "../data/prison-data-2010-2025.xlsx")
```

Visualisation

```{r}
prison_all <- fread("../data/prison-data-2010-2025.csv")
```


```{r}
prison_all[, .(n = sum(value)), 
           .(category, time=ymd(paste(year, month, 15, sep = "-")))] |>
  ggplot(data = _, aes(x = time, y = n, color = category, group = category)) +
  geom_line() +
  labs(x = "Month", y = "Number of people", color = "Category",
       title = "Foreigners in Polish prisons between 2010-04 and 2025-07",
       subtitle = "Based on montly reports by Polish Prison Service") 

ggsave(filename = "../figs/prison-numbers.png", width = 10, height = 6)
```

